
description: An open-source DEM simulation system named REATICLE for granular materials
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
iconfont_url: https://at.alicdn.com/t/font_2714580_eqcgguazg7q.css

author: Y.WANG
email: y.wang@reaticle.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

markdown:         kramdown
highlighter:      rouge



paginate: 7
paginate_path: "/blog/page:num/"